### ISSUE TITLE
Implement mock for findFiles

### ISSUE THREAD

**Issue by poloka** [wcm-io-devops/jenkins-pipeline-library#4]
Would like to see a _findFIlesCallback_ implemented in the LibraryIntegrationTestBase to allow returning of all files that match a pattern provided.  
Example searches:
* findFiles glob: "*.gemspec"
* findFiles glob: "lib/*/version.rb"
* findFiles glob: "src/*.groovy"
* findFiles glob: "my-example.rb"

```
helper.registerAllowedMethod(FIND_FILES, [LinkedHashMap.class], findFilesCallback)
...
def findFilesCallback = {
    Map config ->
    // TODO:
  }
```

Was reviewing the _locateTestResource_ for a possible existing workaround but doesn't account for the fuzzy searches only exact file names.  Initially tried
```
File file = this.dslMock.locateTestResource(config["glob"].toString())
```
But is when discovered the fuzzy search did not work.  I do like being able to drop all resources in the /test/resources folder for any of the searches so would like the findFiles to follow that pattern.

**Comment by tobias-richter** [comment]
@poloka sorry for the late response, this was absolutely not on my radar. I added this to my todo list and will get back to you soon.

**Comment by tobias-richter** [comment]
@poloka please have a look at https://github.com/wcm-io-devops/jenkins-pipeline-library/pull/5 and let me know if that is what you meant.

**Comment by tobias-richter** [comment]
PR merged.
