### ISSUE TITLE
GitRepository.groovy sample

### ISSUE THREAD

**Issue by Giancarlo1974** [wcm-io-devops/jenkins-pipeline-library#41]
it's possible use the jenkins-pipeline-library/src/io/wcm/devops/jenkins/pipeline/scm/GitRepository.groovy

to fetch a branch into workspace ?

Can you post an example ?

**Comment by tobias-richter** [comment]
@Giancarlo1974 no this is not the intention of this class, but have a look at the `checkoutScm` step:

https://github.com/wcm-io-devops/jenkins-pipeline-library/blob/master/vars/checkoutScm.md#example-2-advanced-checkout

**Comment by tobias-richter** [comment]
Closing because there was no update in the issue. Feel free to open the issue again if required.
