### ISSUE TITLE
enum in library accessible from the jenkins pipeline

### ISSUE THREAD

**Issue by ewoks** [wcm-io-devops/jenkins-pipeline-library#59]
is it possible to define enum in library and use its value as a function parameter?
where enum should be located in `src` or `vars`?

**Comment by tobias-richter** [comment]
@ewoks sure, this is possible.

We are using this for our logging:
Enum: https://github.com/wcm-io-devops/jenkins-pipeline-library/blob/master/src/io/wcm/devops/jenkins/pipeline/utils/logging/LogLevel.groovy

Usage:  https://github.com/wcm-io-devops/jenkins-pipeline-library/blob/master/jenkinsfiles/integration-tests.groovy#L64

**Comment by ewoks** [comment]
I thought the same but my Jenkinsfile fails on [import line ](https://github.com/wcm-io-devops/jenkins-pipeline-library/blob/master/jenkinsfiles/integration-tests.groovy#L42) (similar to your import of given example)

**Comment by tobias-richter** [comment]
@ewoks you have to provide detailed information otherwise it is not possible to provide support.
e.g. build error message, how is the pipeline configured, url to the pipeline etc.

**Comment by tobias-richter** [comment]
Closing the issue because no additional input was provided.

**Comment by ewoks** [comment]
Sorry for the late reply, I am on vacations and afk this week. Closing is fine
